### ISSUE TITLE
double output in statusbar

### ISSUE THREAD

**Issue by hoaxdream** [UtkarshVerma/dwmblocks-async#12]
Hi sir, do you know why the blocks doubling up? specially the one with icons. it is fixed if i change the volume, this is common when at first boot of pc.
![Issue](https://i.imgur.com/7n396bt.png)

**Comment by UtkarshVerma** [comment]
Hmm, that's weird. Could you show me your config and the volume script?

**Comment by hoaxdream** [comment]
> Hmm, that's weird. Could you show me your config and the volume script?

i just yours
```sh
. sb-theme
if [ $(pamixer --get-mute) = true ]; then
	display "婢" "$color2"
	exit
fi

vol="$(pamixer --get-volume)"

if [ "$vol" -gt 70 ]; then
	icon=" "
elif [ "$vol" -gt 40 ]; then
	icon="墳 "
elif [ "$vol" -gt 10 ]; then
	icon=" "
else
	icon="奄 "
fi

display "$icon$vol%"
```

**Comment by UtkarshVerma** [comment]
@hoaxdream Thanks for reporting the bug. It should be fixed now. In case there's still an issue, feel free to reopen this issue.
