### ISSUE TITLE
High dwm CPU usage with clickable blocks

### ISSUE THREAD

**Issue by DasHammett** [UtkarshVerma/dwmblocks-async#15]
Hi, 

If I enable `CLICKABLE_BLOCKS` in `config.h` dwm consumes a large amount of CPU power.

I am using dwm-6.3 with statuscmd patch applied and made the modifications as well on `getstatusbarpid()`. Wit the same patches applied, but disabling CLICKABLE_BLOCKS`, dwm behaves normally.

Let me know if you need any other details

Thanks

**Comment by UtkarshVerma** [comment]
Hmm, that's weird. Could you show me which lines you modified exactly?
Also, it would be helpful if you could try out my build of `dwm` and check if you can reproduce this.
https://github.com/UtkarshVerma/dwm
