### ISSUE TITLE
click works only for the first script 

### ISSUE THREAD

**Issue by Mohamed-Fathy-Salah** [UtkarshVerma/dwmblocks-async#17]
hi. 
i enabled the click ability in `config.h` and it worked (runs the scripts) but `BLOCK_BOTTON` only works for the first script
![pic-full-220224-0939-37](https://user-images.githubusercontent.com/60598620/155480000-41989429-4e9b-4f6b-b5ff-4b930f3e89a3.png)
thanks in advance.

**Comment by UtkarshVerma** [comment]
Clickability works fine. You could try referring to my statusbar scripts and maybe you can figure it out.

The action of clickability is simple. You click on a block, dwm sends a signal to dwmblocks. dwmblocks executes the block script with `BLOCK_BUTTON` set.

If you're still facing issues, please elaborate.

**Comment by Mohamed-Fathy-Salah** [comment]
found the error.
use `sh` instead of `zsh` :smile: 
thanks for the reply.
