### ISSUE TITLE
Suggestion: alarm

### ISSUE THREAD

**Issue by explosion-mental** [UtkarshVerma/dwmblocks-async#18]
Hello, what about using `alarm` to notify the parent?

**Comment by UtkarshVerma** [comment]
Are you referring to the SIGALARM signal, or the C function?

**Comment by UtkarshVerma** [comment]
Using this would get rid of the child process, but timing the intervals accurately would be hard.

I'll have a look but AFAIK, using alarm() in the parent will lead to some inaccuracies. If it's within acceptable bounds, then implementing it would be worth it.

**Comment by explosion-mental** [comment]
yeah no need for the timer loop. I've implemented this in my dwm
https://github.com/explosion-mental/Dwm/blob/d056028b8df0d7286df0cf29effa5c296bcbd0d9/dwm.c#L3461
with the same logic of dwmblocks-async

**Comment by explosion-mental** [comment]
> I'll have a look but AFAIK, using alarm() in the parent will lead to some inaccuracies.

Like? I have an interval of `10` seconds. Havent tested with less time. The less you can go is with `1` second, but probably if you have a block update every second would mean to send a signal every seconds and im not sure if thats 'safe' at all.

**Comment by UtkarshVerma** [comment]
That's safe, because signals are queued. What's going to be difficult is only executing alarm() once per interval inside the while loop.

**Comment by explosion-mental** [comment]
calling alarm in the handler, func I showed u above, and [before](https://github.com/explosion-mental/Dwm/blob/d056028b8df0d7286df0cf29effa5c296bcbd0d9/dwm.c#L2962) the loop should do the trick

**Comment by explosion-mental** [comment]
oh and off topic but, thought about using `poll`? only reason being portability I guess
