### ISSUE TITLE
Modules are not clickable

### ISSUE THREAD

**Issue by JimPix1** [UtkarshVerma/dwmblocks-async#21]
Trying to switch to lukes build of dwmblocks to this but it seems to be impossible..
Can't click any modules and I have made the changes to the statuscmd patch (I think I did I did it right, the exact line to change wasn't there but something similar was) so clicking does nothing. I also can't get icons to work unless I change all my scripts to use echo and then echo the icon #20 
FYI I'm using my own build that's based off of Lukes.

**Comment by JimPix1** [comment]
I got Luke's latest dwmblocks and realized that the scrolling bug has been fixed with a pull request.  What I really want now is the asynchronous execution of modules. I have my own update checker that takes several seconds to load on boot/dwmblocks refresh and perhaps if you could guide me as to how I would add the feature into Luke's build? In that case everything would work fine for me.

**Comment by UtkarshVerma** [comment]
Module clickability works fine without any issues. The cause is most likely dwm not sending and signals to the dwmblocks process.

This has already been discussed in #11, so please refer to it for debugging methodology.

**Comment by UtkarshVerma** [comment]
> I got Luke's latest dwmblocks and realized that the scrolling bug has been fixed with a pull request.  What I really want now is the asynchronous execution of modules. I have my own update checker that takes several seconds to load on boot/dwmblocks refresh and perhaps if you could guide me as to how I would add the feature into Luke's build? In that case everything would work fine for me.

For async, the entire approach to the problem changes. Nevertheless, I feel it's a waste of effort to try to integrate two really small projects (~300 lines of code) together.

Just pick whichever one does the job for you.

**Comment by UtkarshVerma** [comment]
> I got Luke's latest dwmblocks and realized that the scrolling bug has been fixed with a pull request.  What I really want now is the asynchronous execution of modules. I have my own update checker that takes several seconds to load on boot/dwmblocks refresh and perhaps if you could guide me as to how I would add the feature into Luke's build? In that case everything would work fine for me.

For async, the entire approach to the problem changes. Nevertheless, I feel it's a waste of your effort to try to integrate two really small projects (~300 lines of code) together.

Just pick whichever one does the job for you.
