### ISSUE TITLE
Clickability without statuscmd patch?

### ISSUE THREAD

**Issue by Tinkerbells** [UtkarshVerma/dwmblocks-async#25]
Hello there, trying to understand what does that block mean "Earlier, dwmblocks-async used to require a patch to be applied to dwm. However, the code has been redone so there's no need to apply that patch anymore." in clickability section. Is it not nessasery to install statuscmd patch? Mine not working without this patch.

**Comment by UtkarshVerma** [comment]
No, you'll need statuscmd as mentioned in the README.
The quoted sentence is referring to another patch which used to be needed but not needed anymore.

**Comment by Tinkerbells** [comment]
And if it still needs is there a proper way to use it with statuscolor and systray?

**Comment by UtkarshVerma** [comment]
It doesn't need it anymore.

To use dwmblocks, just apply the statuscmd patch for clickability and you're good to go.
