### ISSUE TITLE
I Cannot Seem to Set the Update Interval to Less than a Second

### ISSUE THREAD

**Issue by amarakon** [UtkarshVerma/dwmblocks-async#27]
I tried to set the update interval to a millisecond:

```c
#define CMDLENGTH 45
#define DELIMITER " "
#define CLICKABLE_BLOCKS

const Block blocks[] = {
	BLOCK("sb-volume_input",    0.001, 17),
	BLOCK("sb-volume_output",    0.001, 18),
};
```

But it caused it to not update at all.

**Comment by explosion-mental** [comment]
floating numbers aren't supported. the interval value represents the seconds, no decimals.

**Comment by amarakon** [comment]
So does that mean that it is not possible to set the update interval to less than a second? If that is so, can I make it so that my volume scripts update every time I change the volume?

**Comment by explosion-mental** [comment]
ye with signals, `kill(1)` 
see: https://github.com/UtkarshVerma/dwmblocks-async#signalling-changes

**Comment by amarakon** [comment]
That's excellent. That is a great way to have my volume update instantly and efficiently, thanks!
