### ISSUE TITLE
Is is possible to get a signal for mouse hovering

### ISSUE THREAD

**Issue by yogeshdcool** [UtkarshVerma/dwmblocks-async#33]
it would be nice if the block was able to send a signal when mouse is hovering on it 
and it could also change to cursor to pointer when hovering over the block like cursor hinting

**Comment by UtkarshVerma** [comment]
This would be completely up to dwm. For dwmblocks-async, all it cares about is receiving an external event(usually dwm) and once triggered, it will execute the block. Getting the event and deciding what to do based on the event is dwm's responsibility.

Hence I am closing this issue. Feel free to reopen this in the future if you need any help once such a patch for dwm has been written (there aren't any as of now I think).
