### ISSUE TITLE
user-defined signal 1

### ISSUE THREAD

**Issue by sewnie** [UtkarshVerma/dwmblocks-async#4]
clicking on statusbar/module makes dwmblocks-async crash with code 138 output:
```user-defined signal 1 dwmblocks```

this happens when used with my modified dwm build + default dwm only patched with [dwm-statuscmd-status](https://raw.githubusercontent.com/ryotabs/dwm/master/patches/dwm-statuscmd-signal-6.2.diff)

**Comment by Pyxels** [comment]
I have had the same problem, where you able to fix it by just applying the other patch or do I have to completely redo dwm?

**Comment by Pyxels** [comment]
Thanks that fixed the crashing bug.
Though now every click is counted as two, do you have the same problem?
