### ISSUE TITLE
Don't see anything changed

### ISSUE THREAD

**Issue by jbjoeB** [UtkarshVerma/dwmblocks-async#40]
Hello,

I downloaded this from thr repo didn't modify config.h cause the defaults look fine. Did a sudo make install clean. Looked promising. Logged out and back in and dwm status bar is the same. Am I suppose to see something?

I'm new to this so please let me know what I'm doing wrong 

Thanks 

Joe B

**Comment by UtkarshVerma** [comment]
You need to either have my scripts or use your own in `config.h`. You can get my scripts from https://github.com/UtkarshVerma/dotfiles/tree/main/.local/bin/statusbar. Make sure they are in your `PATH` variable.
