### ISSUE TITLE
Some blocks dont update

### ISSUE THREAD

**Issue by sistematico** [UtkarshVerma/dwmblocks-async#43]
![image](https://user-images.githubusercontent.com/97509/216118364-39e27083-9b65-42f7-a078-2620ce3ea618.png)

Config: https://bitbucket.org/sistematico/dwmblocks-async/src/main/
Blocks: https://bitbucket.org/sistematico/dwmblocks-async/src/utils/

Using Void Linux

**Comment by UtkarshVerma** [comment]
Please explain a bit more about the issue.

**Comment by sistematico** [comment]
> Please explain a bit more about the issue.

Sure.

![block](https://user-images.githubusercontent.com/97509/218721385-daeda70d-cf1a-4dae-9bb0-aed1840239f4.png)
Look at block, is showing **1**.

![pgrep](https://user-images.githubusercontent.com/97509/218721489-9199711a-e200-4d6b-936c-191d2dcaf885.png)
Look at pgrep, is showing **2** lines, right?

![pgrep2](https://user-images.githubusercontent.com/97509/218721622-6352049e-b96e-4348-8bb3-50ca509ee788.png)
Look at block last line, its supposed to show 2 instead 1, right?

**Comment by UtkarshVerma** [comment]
Please take time in explaining your issue. I don't understand what you're facing issue with. Blocks are not updating? or the script is not giving the expected output?

Please state the expected behaviour and actual behaviour.
