### ISSUE TITLE
Feedback needed for new changes in `new-org` branch

### ISSUE THREAD

**Issue by UtkarshVerma** [UtkarshVerma/dwmblocks-async#45]
I think I have found a fix #24 . It was pretty simple looking back at it. Anyhow, the fix is in the [new-org](https://github.com/UtkarshVerma/dwmblocks-async/tree/new-org) branch. I was playing around with the build system and code organization, so haven't merged it to `main` yet.

I'm facing the following problem currently, and feedback and help would be highly appreciated:
- I have to define blocks in `blocks.c` for the time being, which isn't good because everything should ideally be in `config.h`.
- I need to find a way for the compiler to dynamically figure out the number of blocks. Currently `N_BLOCKS` macro has to be defined manually, which isn't good.

**Comment by UtkarshVerma** [comment]
Changes have been merged to `main`.

**Comment by hillyu** [comment]
Hey, I think the block script still can be blocked from running, maybe we can just kill the process instead when executing the block, something like:
int block_execute(block *const block, const uint8_t button) {
    // Ensure only one child process exists per block at an instance.
    if (block->fork_pid != -1) {
    /*     return 0; */
        kill(block->fork_pid, 9);
    }
