### ISSUE TITLE
Unable to use scroll inputs (button 4/5)

### ISSUE THREAD

**Issue by 62832** [UtkarshVerma/dwmblocks-async#46]
Been having a go again at ricing in a virtual machine and have been making use so far of this async build of dwmblocks. My only issue at the moment is that it seems like blocks won't respond at all to any scroll inputs (mouse buttons 4 and 5).

I've tried to debug this so far by including a `notify-send "$BLOCK_BUTTON"` line at the start of a block, which indeed throws a notification whenever buttons 1, 2 and 3 are pressed. Otherwise, however, buttons 4 and 5 consistently refuse to throw anything.

Let me know what other info to provide for this issue. I'm also curious as to what input corresponds with button 6, as I have seen this often in different status bar script examples.

**Comment by UtkarshVerma** [comment]
You'll have to configure dwm accordingly.

https://github.com/UtkarshVerma/dwm/blob/mine/config.h#L1436

**Comment by 62832** [comment]
My bad, I knew I was probably missing something obvious. Thanks.
