### ISSUE TITLE
enabling TRAILING_DELIMITER gives error

### ISSUE THREAD

**Issue by yogeshdnumb** [UtkarshVerma/dwmblocks-async#51]
the only thing i changed in config.h (0 to 1) is
`#define TRAILING_DELIMITER 1
` 

it throws this error status.c while using "sudo make clean install"
error/log: 
![2023-11-17_23-38](https://github.com/UtkarshVerma/dwmblocks-async/assets/84368844/ef71f049-1516-4939-8a41-7646c996b824)

> btw thankyou for this awesome project

**Comment by UtkarshVerma** [comment]
Thanks for the bug report. It was a typo and now it's fixed.
