### ISSUE TITLE
show a text for an amount of time when button is pressed, then show another default text

### ISSUE THREAD

**Issue by Mohamed-Fathy-Salah** [UtkarshVerma/dwmblocks-async#58]
When date block is pressed, it should print the output of `date "+%a %d %b "` on the status bar for 3 seconds then it should print the date sybmol.
however it prints the output of `date "+%a %d %b "` only.
![image](https://github.com/UtkarshVerma/dwmblocks-async/assets/60598620/0d5d1f99-906d-40ca-8d77-3990acba13be)

**Comment by UtkarshVerma** [comment]
You got the logic correct for the most part. What you missed is to fork the kill command. This is because `dwmblocks` waits for the current execution to complete and then reads the output.

Here's how you would do this.

```sh
#!/bin/sh

case $BLOCK_BUTTON in
    1)
        echo "A"
        (sleep 3 && pkill -RTMIN+10 dwmblocks) &
        ;;
    *) echo "B" ;;
esac
```

**Comment by Mohamed-Fathy-Salah** [comment]
When it gets pressed, It waits for 3 seconds, then it shows the second text.
However it should show the second text for 3 seconds, then the first text again.

**Comment by Mohamed-Fathy-Salah** [comment]
It got solved using sesid
```bash
#!/bin/sh

case $BLOCK_BUTTON in
    1) 
        setsid -f bash -c 'sleep 3 && kill -35 $(pidof dwmblocks)' >/dev/null 2>&1
        date "+%a %d %b " ;;
    *) echo '';;
esac
```
