### ISSUE TITLE
dwmblocks not working as expected

### ISSUE THREAD

**Issue by jb1277976** [UtkarshVerma/dwmblocks-async#60]
I'm still kinda new to the linux scene.

Installed dwmblocks today added dwmblocks & to my .xinintrc and when i rebooted it's not working.

[I got this](https://dpaste.org/FQKjm)

What am i doing wrong?

What are the programs or scripts that start with sb-

I just installed arch 2 days ago, coming from gentroo

Thanks

~ Joe B

**Comment by DusanLesan** [comment]
It seems that the scripts referenced in your configuration file (blocks from the config.h) are not present in your path. These blocks in the config.h are merely examples of how to configure dwmblocks. The actual scripts used in the configuration can be found here: https://github.com/UtkarshVerma/dotfiles/tree/main/.local/bin/statusbar. You need to place them in a directory that is included in your PATH.

**Comment by UtkarshVerma** [comment]
Thanks @DusanLesan for the clarification. Closing this since that's the solution. Please take a look at the README for configuration details.
