### ISSUE TITLE
How do I get colored status bat in dwm?

### ISSUE THREAD

**Issue by SisyphusIsntHappy** [UtkarshVerma/dwmblocks-async#61]
I noticed colored text in you example screenshot.
How do I get this?

Regards

**Comment by UtkarshVerma** [comment]
dwmblocks only sends plain text to dwm. To get colored status, you'll have to use patches like https://dwm.suckless.org/patches/statuscolors/ that enable it.

**Comment by lotigara** [comment]
I have also noticed the colored text. You've already clarified things on the dwm side, but what is left with dwmblocks?

**Comment by UtkarshVerma** [comment]
You'll have to update your scripts to send the correct bytes for the color. It's explained in the patch I linked.
