### ISSUE TITLE
unable to refresh all blocks without crashing

### ISSUE THREAD

**Issue by Zerogaku** [UtkarshVerma/dwmblocks-async#63]
Hi before the rewrite I used to do be able to refresh all blocks with:
`pkill -SIGUSR1 dwmblocks`
or
`kill -10 $(pidof dwmblocks)`

but now they just crash dwmblocks, this is the build where those commands still work https://github.com/Zerogaku/Abyss-dwmblocks/tree/main

I currently use:
```
pkill 'dwmblocks' && \
dwmblocks & \
```
as a working alternative

**Comment by UtkarshVerma** [comment]
Thanks for the bug report. I have fixed the bug now.
