### ISSUE TITLE
Special delimiter for each block

### ISSUE THREAD

**Issue by salastro** [UtkarshVerma/dwmblocks-async#64]
Hello, in my dwm, I am using powerline patch, and in my config, I want each block to have a different leading delimiter. I thought about implementing this myself but was unable to navigate the codebase after the rewrite.

**Comment by salastro** [comment]
I believe in the older dwmblocks, this was called "icon"

**Comment by UtkarshVerma** [comment]
I forgot to add this in my build but it has been added now. Thanks for letting me know.

**Comment by DusanLesan** [comment]
This fixes #30 in a way I wanted it to look since I can just add space to first block
