### ISSUE TITLE
icons rendering as empty squares

### ISSUE THREAD

**Issue by bwkam** [UtkarshVerma/dwmblocks-async#65]
hello, my icons aren't rendering properly, I'm not sure why.
![image](https://github.com/UtkarshVerma/dwmblocks-async/assets/91009118/ebbbf291-1f07-4cf3-86f7-3b3caab15a7a)

**Comment by UtkarshVerma** [comment]
You'll have to configure dwm to use a font that has the glyphs. Not a concern for this repo.

**Comment by bwkam** [comment]
Ah, sorry. Thanks.
