### ISSUE TITLE
2 finger scroll not doing anything

### ISSUE THREAD

**Issue by yogeshdofficial** [UtkarshVerma/dwmblocks-async#66]
4) wpctl set-volume @DEFAULT_AUDIO_SINK@ 1%+ ;;
5) wpctl set-volume @DEFAULT_AUDIO_SINK@ 1%- ;;

I have this a part of my script and 2 finger scroll is button 4 and 5 (shown by xev) but they are not doing anything
I don't have a physical mouse to test and wanted to whether 2 finger scroll counts as mouse scroll

**Comment by UtkarshVerma** [comment]
You'll have to configure dwm for this.
