### ISSUE TITLE
Glyphs not rendering properly

### ISSUE THREAD

**Issue by neerajnangireddy** [UtkarshVerma/dwmblocks-async#67]
I am using Debian bookworm stable and `dwm 6.5 ` .
I have followed the instruction from the README and downloaded dwmblocks-async and installed it.
I also downloaded the status bar scripts from your dot files.
If I run the scripts from terminal the glyph s are rendered properly but when I run dwmblocks  the glyph s are not rendering correctly.
I am using `JetBrainsMono Nerd Font Mono` as my font for dwm and terminal(alacritty)

The fonts specified in dwm are like this 
`static const char *fonts[]          = { "JetBrainsMono Nerd Font Mono:size=14:antialias=true:autohint=true;monospace:size=12" };`.
![ksnip_20240712-183039](https://github.com/user-attachments/assets/8be1dd88-9cbb-4f0b-add0-f46a07225a5d)

surprisingly if I use xsetroot to display output of any status bar script of yours works fine.
![ksnip_20240712-185046](https://github.com/user-attachments/assets/ac54d9f3-b415-4fa3-99eb-95663b254a15)

running from terminal
![ksnip_20240712-185335](https://github.com/user-attachments/assets/d59548d0-068b-4f30-ae76-1a369d0f431e)

**Comment by 2084x** [comment]
try installing `ttf-dejavu`

**Comment by Abhra00** [comment]
Try removing the mono at last
Name should be "JetbrainsMono Nerd Font"

**Comment by neerajnangireddy** [comment]
> Try removing the mono at last Name should be "JetbrainsMono Nerd Font"

Nope. Doesn't Work

**Comment by neerajnangireddy** [comment]
> try installing `ttf-dejavu`

This works
But I don't like Dejavu font.
Anyway I switched to [slstatus](https://git.suckless.org/slstatus) and happy with it

**Comment by 2084x** [comment]
you don't actually have to use the dejavu font, just have it installed.

**Comment by neerajnangireddy** [comment]
> you don't actually have to use the dejavu font, just have it installed.

ok
