### ISSUE TITLE
Pair with splitstatus

### ISSUE THREAD

**Issue by thmsdelange** [UtkarshVerma/dwmblocks-async#69]
Hi, first of all thank you for your very useful implementation of dwmblocks. 
I know this is not related to your implementation of dwmblocks itself but I was wondering if you know a way to pair dwmblocks with the [splitstatus](https://dwm.suckless.org/patches/splitstatus/) patch? I would like to center my clock in the statusbar while still have all the dwmblocks features on the right of the bar. Do you know a way to implement this?

**Comment by UtkarshVerma** [comment]
It's not directly supported, and probably would never be. But what you could do is just have an "echo \<delim\>" command as a block that never updates.
