### ISSUE TITLE
[1]  + user-defined signal 1  dwmblocks

### ISSUE THREAD

**Issue by se7en-x230** [UtkarshVerma/dwmblocks-async#7]
When I use Lukes scripts I get `[1]  + user-defined signal 1  dwmblocks` whenever I click on the block.

**Comment by Pyxels** [comment]
Have a look at Issue #4, probably the same thing.

**Comment by UtkarshVerma** [comment]
@se7en-x230 This is same as #4 . Therefore closing this as a duplicate.
