### ISSUE TITLE
[enhancement] be able to the clickable blocks feature

### ISSUE THREAD

**Issue by wael444** [UtkarshVerma/dwmblocks-async#8]
might entirely avoid one of the main features of dwmblocks-async, but i only put this up since i use a dwm build without statuscmd for practical reasons, or i could use [dwmblocks](https://github.com/torrinfail/dwmblocks) but i will eventually lose the *async* feature.

**Comment by UtkarshVerma** [comment]
I think it's not a bad idea to have this configurable as well. Therefore, it has been implemented through 3d55e4b10ffcb11378b0f2770b91358b0eef948a.

From now on, setting the `CLICKABLE_BLOCKS` macro has to be defined in `config.h` to enable clickability.
Please feel free to close the issue if you don't face any issues.

**Comment by wael444** [comment]
thank you!
